indent = 4
margin = 120
always_use_return = false
short_to_long_function_def = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
always_for_in = true
import_to_using = false
pipe_to_function_call = false
whitespace_in_kwargs = true
annotate_untyped_fields_with_any = false
separate_kwargs_with_semicolon = true
join_lines_based_on_source = true
indent_submodule=true
normalize_line_endings="unix"